### ISSUE TITLE
The decryption error 

### ISSUE THREAD

**Issue by floorstyle** [Mastercard/client-encryption-go#1]
Hi, 

If the `pkc12` file will be used as `decryptionKey`, the `encryption.DecryptPayload` returns an error: `panic: crypto/rsa: decryption error`. Is it intended?

Regards, Daniyar.

**Comment by danny-gallagher** [comment]
Hi @floorstyle,

Can you provide more details on the error that you're facing? Is this a p12 file that you're downloading from Mastercard Developers? If so, can you provide us with more details as to where/when the error is occurring?

We do have a test that loads a p12 file [here](https://github.com/Mastercard/client-encryption-go/blob/master/utils/encryption_utils_test.go#L22).

**Comment by floorstyle** [comment]
Hi @danny-gallagher , 
So I have tried the `p12` tested key in this [test](https://github.com/Mastercard/client-encryption-go/blob/fcaa30c4f2e60c062abab84aa2160b499b606eb6/encryption/encryption_test.go#L12)  and got an error. 

```
func TestEncryptPayload_ShouldEncryptRootArrays(t *testing.T) {
	payload := "[" +
		"   {}," +
		"   {}" +
		"]"

	decryptionKeyPath := "../testdata/keys/pkcs12/test_key.p12"
	certificatePath := "../testdata/certificates/test_certificate-2048.der"
	password := "Password1"

	decryptionKey, err := utils.LoadDecryptionKey(decryptionKeyPath, password)
	assert.Nil(t, err)
	certificate, err := utils.LoadEncryptionCertificate(certificatePath)
	assert.Nil(t, err)

	cb := jwe.NewJWEConfigBuilder()
	jweConfig := cb.WithDecryptionKey(decryptionKey).
		WithEncryptionPath("$", "$").
		WithDecryptionPath("encryptedData", "$").
		WithEncryptedValueFieldName("encryptedData").
		WithCertificate(certificate).
		Build()

	encryptedPayload := encryption.EncryptPayload(payload, *jweConfig)
	decryptedPayload := encryption.DecryptPayload(encryptedPayload, *jweConfig)

	assert.Equal(t, "[{},{}]", decryptedPayload)
}

```

Am I doing anything wrong?

**Comment by danny-gallagher** [comment]
Hi @floorstyle,

Can you try following the steps outlined [here](https://developer.mastercard.com/platform/tutorial/use-postman-for-mastercard-apis/step-2/) to convert your .p12 file to an RSA .key and let us know if this works for you?

```openssl pkcs12 -in '<location of the .p12 file>' | openssl rsa -out <Filename of the key generated ending with .key>```

**Comment by floorstyle** [comment]
Hi! @danny-gallagher, I've tried your suggestion, unfortunately still got an error: 

```

func TestEncryptPayload_ShouldEncryptRootArrays(t *testing.T) {
	payload := "[" +
		"   {}," +
		"   {}" +
		"]"

	decryptionKeyPath := "../testdata/keys/pkcs12/new.key"
	certificatePath := "../testdata/certificates/test_certificate-2048.der"

	decryptionKey, err := utils.LoadUnencryptedDecryptionKey(decryptionKeyPath)
	assert.Nil(t, err)
	certificate, err := utils.LoadEncryptionCertificate(certificatePath)
	assert.Nil(t, err)

	cb := jwe.NewJWEConfigBuilder()
	jweConfig := cb.WithDecryptionKey(decryptionKey).
		WithEncryptionPath("$", "$").
		WithDecryptionPath("encryptedData", "$").
		WithEncryptedValueFieldName("encryptedData").
		WithCertificate(certificate).
		Build()

	encryptedPayload := encryption.EncryptPayload(payload, *jweConfig)
	decryptedPayload := encryption.DecryptPayload(encryptedPayload, *jweConfig)

	assert.Equal(t, "[{},{}]", decryptedPayload)
}
```
<img width="715" alt="Screenshot 2022-11-17 at 18 06 58" src="https://user-images.githubusercontent.com/52888045/202442293-20df403d-0846-46d0-83ed-a5311fed74ef.png">
<img width="1129" alt="Screenshot 2022-11-17 at 18 09 25" src="https://user-images.githubusercontent.com/52888045/202442549-52579f3c-b698-4424-9bba-e0ec7532d5f5.png">

**Comment by danny-gallagher** [comment]
Hi @floorstyle, it looks like the error you're getting above is actually related to the decryption process, and not with the loading of the decryption key.

The decryption (private) key you're using to decrypt the payload isn't associated with the encryption (public) certificate used to encrypt the payload.

Have you tried using the RSA (.key) file to decrypt an encrypted response from a Mastercard service?

**Comment by danny-gallagher** [comment]
Closing issue
