### ISSUE TITLE
How can i have all the required fields for encryption of Confirmed Frauds api?

### ISSUE THREAD

**Issue by mateusmrangel** [Mastercard/client-encryption-go#3]
Using this lib i just get the encryptedData field. 

i should have also:

                    .withEncryptedKeyFieldName("encryptedKey")
                    .withOaepPaddingDigestAlgorithmFieldName("oaepHashingAlgorithm")
                    .withEncryptionKeyFingerprintFieldName("publicKeyFingerprint")
                    .withIvFieldName("iv")

**Comment by mateusmrangel** [comment]
As a result, my json payload is only having the encryptedData field. And the issuer-frauds POST endpoint is returning 500

**Comment by mateusmrangel** [comment]
Hmm

It seens that this client-encryption-go library only implements JWE Encryption

And the confirmed-frauds api onyl accepts Mastercard Encryption (aka Field Level Encryption)

**Comment by mateusmrangel** [comment]
Can i have some help? @danny-gallagher @talha-API 

i already developed the full system in go

**Comment by danny-gallagher** [comment]
Hi @mateusmrangel,

As you've observed, the go library only supports JWE encryption.
Unfortunately we won't be updating the library to support Mastercard Encryption.

Apologies for any inconvenience caused by this.
