### ISSUE TITLE
Error in README for encryption

### ISSUE THREAD

**Issue by kaischwanke** [Mastercard/client-encryption-go#7]
https://github.com/Mastercard/client-encryption-go/blob/938946b415bbd96beb6a4753f646388e2c3f0b01/README.md?plain=1#L206

Should this line say:
`WithEncryptionPath("$", "$").`
?

**Comment by danny-gallagher** [comment]
> https://github.com/Mastercard/client-encryption-go/blob/938946b415bbd96beb6a4753f646388e2c3f0b01/README.md?plain=1#L206
> 
> Should this line say: `WithEncryptionPath("$", "$").` ?

Hi @kaischwanke. This library supports field level encryption.
The encryption path can be used to encrypt/decrypt a specific path/element in the payload.

When an encryption/decryption path of "$" is given then the entire payload is encrypted/decrypted.
However you can also pass something like:```WithEncryptionPath("$.foo", "$.encryptedFoo")```.
This will then encrypt the "foo" element to a new "encryptedFoo" element with the encrypted payload.

See here for an example:
https://github.com/Mastercard/client-encryption-go#-configuring-the-jwe-encryption-

**Comment by kaischwanke** [comment]
Hi @danny-gallagher , thanks for your reply.
I do understand the syntax. However, I am referring to the README about "Encrypting Entire Payloads". 
Is says to use `"$" operator as encryption path`.
But then in the example below, it shows field level encryption. It might be a copy&paste error?

**Comment by danny-gallagher** [comment]
> Hi @danny-gallagher , thanks for your reply. I do understand the syntax. However, I am referring to the README about "Encrypting Entire Payloads". Is says to use `"$" operator as encryption path`. But then in the example below, it shows field level encryption. It might be a copy&paste error?

Apologies @kaischwanke, you're right! We've updated the README to reflect the correct configuration.
Thanks for pointing out this inconsistency!
