### ISSUE TITLE
Mastercard Encryption and Decryption

### ISSUE THREAD

**Issue by thanh-phong-dev** [Mastercard/client-encryption-go#9]
Hi Mastercard team, Could you guys additional Mastercard Encryption in Golang?
https://github.com/Mastercard/client-encryption-csharp#mastercard-encryption-and-decryption

**Comment by rfeelin** [comment]
Hi @thanh-phong-dev 
Thanks for bringing this to our attention. We'll add it to our backlog and let you know once we've added it in.

**Comment by thanh-phong-dev** [comment]
thanks @rfeelin

**Comment by danny-gallagher** [comment]
Addressing this issue in the following PR: https://github.com/Mastercard/client-encryption-go/pull/14

**Comment by danny-gallagher** [comment]
> Addressing this issue in the following PR: #14

FYI: https://github.com/Mastercard/client-encryption-go/releases/tag/v1.1.0
